/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "primary": "#00e1ab",
        "primary-dim": "#00d19f",
        "primary-container": "#00513c",
        "primary-fixed": "#47fec6",
        "primary-fixed-dim": "#2fefb8",
        "on-primary": "#004a36",
        "on-primary-container": "#26ebb4",
        "on-primary-fixed": "#004935",
        "on-primary-fixed-variant": "#00684e",
        "inverse-primary": "#006c51",
        "secondary": "#78a3bf",
        "secondary-dim": "#78a3bf",
        "secondary-container": "#0a4058",
        "secondary-fixed": "#c5e7ff",
        "secondary-fixed-dim": "#aedaf8",
        "on-secondary": "#002333",
        "on-secondary-container": "#99c5e2",
        "on-secondary-fixed": "#11445c",
        "on-secondary-fixed-variant": "#33607a",
        "tertiary": "#fbf9f8",
        "tertiary-dim": "#edeaea",
        "tertiary-container": "#edeaea",
        "tertiary-fixed": "#f5f3f3",
        "tertiary-fixed-dim": "#e7e5e4",
        "on-tertiary": "#5f5f5f",
        "on-tertiary-container": "#575757",
        "on-tertiary-fixed": "#4a4949",
        "on-tertiary-fixed-variant": "#666666",
        "surface": "#0e0e0e",
        "surface-dim": "#0e0e0e",
        "surface-bright": "#2b2c2d",
        "surface-tint": "#00e1ab",
        "surface-variant": "#242627",
        "surface-container": "#191a1a",
        "surface-container-low": "#131314",
        "surface-container-high": "#1f2020",
        "surface-container-highest": "#242627",
        "surface-container-lowest": "#000000",
        "on-surface": "#e6e5e6",
        "on-surface-variant": "#ababab",
        "on-background": "#e6e5e6",
        "background": "#0e0e0e",
        "outline": "#757576",
        "outline-variant": "#474849",
        "inverse-surface": "#fbf9f8",
        "inverse-on-surface": "#555555",
        "error": "#ee7d77",
        "error-dim": "#bb5551",
        "error-container": "#7f2927",
        "on-error": "#490106",
        "on-error-container": "#ff9993",
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Space Grotesk", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
}
